---
become_override: False
ocp_username: kubeadmin
ocp_workload: ocp4-workload-rhte-kubefed-app-portability
silent: False

ACTION: "provision"

_argocd_project: "argocd"
_argocd_project_display: "ArgoCD Server"
_argocd_server_deployment: "argocd-server"
_argocd_default_user: "admin"
_argocd_default_user_password: "r3dh4t1!"

_gogs_project: "gogs"
_gogs_project_display: "Gogs Git Server"
_gogs_server_deployment: "gogs"
_gogs_db_name: "gogs"
_gogs_db_user: "gogs"
_gogs_db_user_password: "gogs"
_gogs_db_admin_password: "g0gsadm1n"
_gogs_webhook_tls_verify: "false"
_gogs_default_user: "student"
_gogs_default_user_password: "r3dh4t1!"
_gogs_default_user_mail: "admin@techexchan.ge"

_kubefedctl_release: "0.1.0-rc4"
_cfssl_release: "R1.2"
_argocd_release: "v1.0.2"

_lab_git_repo: "https://github.com/davidszegedi/federation-dev"
_lab_git_repo_branch: "master"
_lab_git_clone_dir_name: "federation-dev-github"
_lab_gogs_repo_name: "federation-dev"
_lab_gogs_repo_branch: "master"
_lab_gogs_clone_dir_name: "federation-dev"


_clientvm_student_user: "user1"
_clientvm_student_user_group: "user1"
