---
_lab_gogs_clone_dir_name: "federation-dev"
var_certdir_name: "certs"
var_user_homepath: "/home/user1"
var_demofolder_name: "fed-ocp-demo"

deploy_app_pacman: 'false'
deploy_app_overlay_pacman: 'false'
restore_app_overlay_mongo: 'false'
restore_app_overlay_pacman: 'false'
app_image_src: "quay.io/rcook/pacman-nodejs-app-pipeline:latest"

#demo_cluster: cluster1
overlay_cluster: cluster1

_clientvm_student_user: "user1"
_argocd_project: "argocd"
_argocd_project_display: "ArgoCD Server"
_argocd_server_deployment: "argocd-server"
_argocd_default_user: "admin"
_argocd_default_user_password: "r3dh4t1!"


var_cluster_info:
  - { name: cluster1, region: eu-west-3, deploy: true }
  - { name: cluster2, region: eu-central-1, deploy: true }
  - { name: cluster3, region: eu-west-1, deploy: true }
  - { name: cluster4, region: francecentral, destroy: true }

var_cluster_list:
  - cluster1
  - cluster2
  - cluster3
