---
- name: Copy mongofed base folder
  copy:
    src: "{{ var_user_homepath }}/Git/{{ _lab_gogs_clone_dir_name }}/labs/lab-6-assets/base"
    dest: "{{ var_user_homepath }}/{{ var_demofolder_name }}/{{ var_mongofed_configfolder_name }}/base"

- name: Copy mongofed overlays folder
  copy:
    src: "{{ var_user_homepath }}/Git/{{ _lab_gogs_clone_dir_name }}/labs/lab-6-assets/overlays"
    dest: "{{ var_user_homepath }}/{{ var_demofolder_name }}/{{ var_mongofed_configfolder_name }}/overlays"
