---
- name: Copy certs folder
  copy:
    src: "{{ var_user_homepath }}/{{ var_demofolder_name }}/{{ var_certdir_name }}/"
    dest: "{{ var_user_homepath }}/Git/{{ _lab_gogs_clone_dir_name }}/labs/lab-6-assets"

- name: Update mongodb.pem
  shell: "sed -i \"s/mongodb.pem: .*$/mongodb.pem: $(openssl base64 -A < mongo.pem)/\" base/mongo-secret.yaml"
  args:
    chdir: "{{ var_user_homepath }}/Git/{{ _lab_gogs_clone_dir_name }}/labs/lab-6-assets"

- name: Update ca.pem
  shell: "sed -i \"s/ca.pem: .*$/ca.pem: $(openssl base64 -A < ca.pem)/\" base/mongo-secret.yaml"
  args:
    chdir: "{{ var_user_homepath }}/Git/{{ _lab_gogs_clone_dir_name }}/labs/lab-6-assets"
