---
- name: Get {{ var_occlient_filename }} file
  get_url:
    url: "{{ var_ocpinstall_url }}{{ var_occlient_filename }}"
    dest: "{{ var_user_homepath }}/{{ var_demofolder_name }}/utils"

- name: Ensure binaries dir exists
  file:
    path: "{{ var_user_homepath }}/bin/"
    state: directory
    mode: '0755'

- name: Extract oc client
  unarchive:
    src: "{{ var_user_homepath }}/{{ var_demofolder_name }}/utils/{{ var_occlient_filename }}"
    dest: "{{ var_user_homepath }}/bin/"

- name: Get {{ var_kubefedctl_filename }} file
  get_url:
    url: "{{ var_kubefedctl_url }}{{ var_kubefedctl_filename }}"
    dest: "{{ var_user_homepath }}/{{ var_demofolder_name }}/utils"

- name: Extract kubefedctl client
  unarchive:
    src: "{{ var_user_homepath }}/{{ var_demofolder_name }}/utils/{{ var_kubefedctl_filename }}"
    dest: "{{ var_user_homepath }}/bin/"

- name: Get {{ var_cfssl_filename }} file
  get_url:
    url: "{{ var_cfssl_path }}{{ var_cfssl_filename }}"
    dest: "{{ var_user_homepath }}/{{ var_demofolder_name }}/utils"

- name: Copy cfssl to bin folder
  copy:
    src: "{{ var_user_homepath }}/{{ var_demofolder_name }}/utils/{{ var_cfssl_filename }}"
    dest: "{{ var_user_homepath }}/bin/cfssl"
    mode: u+x,g+x,o+x

- name: Get {{ var_cfssljson_filename }} file
  get_url:
    url: "{{ var_cfssl_path }}{{ var_cfssljson_filename }}"
    dest: "{{ var_user_homepath }}/{{ var_demofolder_name }}/utils"

- name: Copy cfssljson to bin folder
  copy:
    src: "{{ var_user_homepath }}/{{ var_demofolder_name }}/utils/{{ var_cfssljson_filename }}"
    dest: "{{ var_user_homepath }}/bin/cfssljson"
    mode: u+x,g+x,o+x
