---
_lab_gogs_clone_dir_name: "federation-dev"
var_certdir_name: certs
var_user_homepath: "/home/user1"
var_demofolder_name: fed-ocp-demo

var_primary_node: mongo-cluster1.apps.cluster1.rheventdemo.com:443
var_secondary_node: mongo-cluster2.apps.cluster2.rheventdemo.com:443
var_third_node: mongo-cluster3.apps.cluster3.rheventdemo.com:443
var_replica_members: mongo-cluster1.apps.cluster1.rheventdemo.com:443,mongo-cluster2.apps.cluster2.rheventdemo.com:443,mongo-cluster3.apps.cluster3.rheventdemo.com:443

_clientvm_student_user: "user1"
_argocd_project: "argocd"
_argocd_project_display: "ArgoCD Server"
_argocd_server_deployment: "argocd-server"
_argocd_default_user: "admin"
_argocd_default_user_password: "r3dh4t1!"


var_cluster_info:
  - { name: cluster1, region: eu-west-3, deploy: true }
  - { name: cluster2, region: eu-central-1, deploy: true }
  - { name: cluster3, region: eu-west-1, deploy: true }

var_cluster_list:
  - cluster1
  - cluster2
  - cluster3
