---
var_cluster_info:
  - { name: cluster1, region: eu-west-3, deploy: true }
  - { name: cluster2, region: eu-central-1, deploy: true }
  - { name: cluster3, region: eu-west-1, deploy: true }

var_cluster_list:
  - cluster1
  - cluster2
  - cluster3

var_certdir_name: certs
#var_kube_concat_name: kube-concat-auth
var_user_homepath: "/home/user1"
var_demofolder_name: fed-ocp-demo
var_mongofed_configfolder_name: mongofed
#var_kubeconfigfolder_name: auth-fed
#var_kubefed_operator: cluster01
#var_kubeconfig_path: "~/{{ var_demofolder_name }}/{{ var_kubefed_operator }}/auth/kubeconfig"
#var_kubeconfig_concat_path: "~/{{ var_demofolder_name }}/{{ var_kubeconfigfolder_name }}/{{ var_kube_concat_name }}"

install_state: present

#var_kubefed_scope: Cluster
#var_kubefed_scope: Namespaced
#ar_obj_kind: KubeFed
#var_obj_metadata_name: kubefed-resource
#var_obj_spec_targetnamespace: "{{ var_csc_spec_targetnamespace }}"

#var_fed_obj_list:
#  - namespaces
#  - deployments.apps
#  - ingresses.extensions
#  - secrets
#  - serviceaccounts
#  - services
#  - persistentvolumeclaims
#  - configmaps
#  - scc

var_mongodb_pem_data_path: "{{ var_user_homepath }}/{{ var_demofolder_name }}/{{ var_certdir_name }}/mongo.pem"
var_ca_pem_data_path: "{{ var_user_homepath }}/{{ var_demofolder_name }}/{{ var_certdir_name }}/ca.pem"
var_mongodb_pem_data: "{{ lookup('file', var_mongodb_pem_data_path) | b64encode }}"
var_ca_pem_data: "{{ lookup('file', var_ca_pem_data_path) | b64encode }}"

var_mongo_db_external_port: 27017
var_mongo_db_internal_port: 27017

var_mongofed_service: mongo
var_mongofed_namespace: mongo

var_primary_node: mongo-cluster1.apps.cluster01.rheventdemo.com:443
var_replica_members: mongo-cluster1.apps.cluster01.rheventdemo.com:443,mongo-cluster2.apps.cluster02.rheventdemo.com:443,mongo-cluster3.apps.cluster03.rheventdemo.com:443

var_oc_operation: create
