---
- name: Create {{ var_kubeconfigfolder_name }} config folder
  file:
    path: "{{ var_user_homepath }}/{{ var_demofolder_name }}/{{ var_kubeconfigfolder_name }}"
    state: directory

- name: Create default .kube directory
  file:
    path: "{{ var_user_homepath }}/.kube"
    state: directory

- name: Backup kubeconfig files
  copy:
    src: "{{ var_user_homepath }}/{{ var_demofolder_name }}/{{ item.name }}/auth/kubeconfig"
    dest: "{{ var_user_homepath }}/{{ var_demofolder_name }}/{{ item.name }}/auth/bkp_kubeconfig"
  loop: "{{ var_cluster_info }}"

- name: Modify kubeconfig files
  replace:
    path: "{{ var_user_homepath }}/{{ var_demofolder_name }}/{{ item.name }}/auth/kubeconfig"
    regexp: 'admin'
    replace: "{{ item.name }}"
  loop: "{{ var_cluster_info }}"

- name: Concatenate kubeconfig paths
  set_fact:
    kube_concat_path: "{{ var_cluster_info | json_query('[*].name') | map('regex_replace', '^(.*)$', '{{ var_user_homepath }}/' {{ var_user_homepath }} var_demofolder_name {{ var_user_homepath }} '/\\1/auth/kubeconfig') | map('expanduser') | join(':') }}"
    kube_concat_name: "aws-{{ var_cluster_info | json_query('[*].name') | join('-') }}"

- name: Flatten kube concat path
  command: ./oc config view --flatten
  args:
    chdir: "{{ '{{ var_user_homepath }}/bin' | expanduser }}"
    creates: /tmp/flattenkube.out
  environment:
    KUBECONFIG: "{{ kube_concat_path }}"
  register: occfgv_flatten

- name: Copy kubeconfig content to {{ var_kube_concat_name }}
  copy:
    content: "{{ occfgv_flatten.stdout }}"
    dest: "{{ var_user_homepath }}/{{ var_demofolder_name }}/{{ var_kubeconfigfolder_name }}/{{ var_kube_concat_name }}"

- name: Copy kubeconfig content to .kube
  copy:
    content: "{{ occfgv_flatten.stdout }}"
    dest: "{{ var_user_homepath }}/.kube/config
