---
#- name: Update application image
#  shell: "sed -i \"s~quay.io.*~{{ app_image_src }}~g\" overlay/{{ overlay_cluster }}/pacman-deployment.yaml"
#  args:
#    chdir: "{{ var_user_homepath }}/Git/{{ _lab_gogs_clone_dir_name }}/labs/lab-7-assets"

- name: Update application application image
  template:
    src: pacman-deployment.j2
    dest: "{{ var_user_homepath }}/Git/{{ _lab_gogs_clone_dir_name }}/labs/lab-7-assets/overlay/{{ overlay_cluster }}/pacman-deployment.yaml"

- name: Commit changes to cluster {{ overlay_cluster }}
  shell: "git commit -am 'new image to cluster' && git push origin master"
  args:
    chdir: "{{ var_user_homepath }}/Git/{{ _lab_gogs_clone_dir_name }}/labs/lab-7-assets"

- name: Place new Pacman image to cluster {{ overlay_cluster }}
  shell: /usr/local/bin/argocd --insecure --grpc-web login $(oc --context cluster1 -n argocd get route argocd-server -o jsonpath="{.status.ingress[*].host}{\"\n\"}"):443 --username {{ _argocd_default_user }} --password {{ _argocd_default_user_password }}; argocd app sync {{ overlay_cluster }}-pacman; wait-for-argo-app {{ overlay_cluster }}-pacman
  args:
    chdir: "{{ var_user_homepath }}"
  become: true
  become_user: "{{ _clientvm_student_user }}"
