---
- include: deploy-app.yml
  when: deploy_app == 'true'

- include: deploy-app-overlay.yml
  when: deploy_app_overlay == 'true'

- include: restore-app-overlay-mongo.yml
  when: restore_app_overlay_mongo == 'true'

- include: restore-app-overlay-pacman.yml
  when: restore_app_overlay_pacman == 'true'
